# -*- coding: utf-8 -*-

# request
ERR_CODE_INVALID_REQUEST_METHOD = 1000
ERR_CODE_INVALID_REQUEST_PARAM= 1001
ERR_CODE_VALIDATE = 1002

# auth
ERR_CODE_AUTH_ERROR = 2000

# remote app agent
ERR_CODE_REMOTE_APP_AGENT_ERROR = 3000
ERR_CODE_REMOTE_APP_AGENT_RETURN_DATA_FORMAT_ERROR = 3001

#server
ERR_CODE_INTERNAL_ERROR = 5000

# llm
ERR_CODE_LLM_REPLY = 6000
ERR_CODE_LLM_MODEL_NAME = 6100